//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpComputer.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpComputer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 I7000=6527
        ///I7001=0 
        ///I7002=3
        ///I10=3713991
        ///
        ///
        ///I100=1
        ///I101=0
        ///
        ///
        ///I7010=8
        ///
        ///
        ///I7016=3
        ///I102=$078004
        ///
        ///;I124=$120001
        ///;I125=$078000 
        ///
        ///
        ///I124=$100001  
        ///I125=$078000 
        ///
        ///
        ///I113=10000000
        ///I114=-10000000
        ///
        ///
        ///I130=10500 
        ///I131=500   
        ///I132=30  
        ///I133=10  
        ///I134=1  
        ///I135=0   
        ///I136=0	
        ///I137=0   
        ///
        ///
        ///I119=5
        ///I120=25
        ///I121=8
        ///I122=20
        ///I122=32
        ///
        ///I200=1
        ///I201=0
        ///
        ///I7020=8 
        ///I203=$3502
        ///I204=$3502
        ///I208=96
        ///
        ///
        ///I7026=3
        ///I202=$7800C
        ///
        ///
        ///
        ///I224=$120001
        ///I225=$078008 
        ///
        ///
        ///
        ///I213=10000000
        ///I214=-10000000
        ///
        ///
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string _1_2号电机I变量配置 {
            get {
                return ResourceManager.GetString("_1_2号电机I变量配置", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 M120-&gt;X:$078000,16 ; /*HOME限位标志，常高电平*/ 
        ///M121-&gt;X:$078000,17 ; /*正限位标志，常低电平*/  
        ///M122-&gt;X:$078000,18 ; /*负限位标志，常低电平*/
        ///
        ///M172-&gt;L:$0000D7 ; #1 变量手动位置/距离 (计数)
        ///M140-&gt;Y:$0000C0,0,1 ; #1 后台在位位，运行时为0，Jog到位后为1
        ///M162-&gt;D:$00008B ; #1 实际位置 (1/[Ixx08*32] cts)
        ///M117-&gt;X:$078000,11 ; ENC1 捕捉标志
        ///
        ///M220-&gt;X:$078008,16 ; /*HOME限位标志，常高电平*/ 
        ///M221-&gt;X:$078008,17 ; /*正限位标志，常低电平*/  
        ///M222-&gt;X:$078008,18 ; /*负限位标志，常低电平*/
        ///
        ///M272-&gt;L:$000157 		;#2 变量手动位置/距离 (计数)
        ///M240-&gt;Y:$000140,0,1 	;#2 后台在位位，运行时为0，Jog到位后为1
        ///M262-&gt;D:$00010B 		;#2 实际位 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 两轴回零PLC启动程序 {
            get {
                return ResourceManager.GetString("两轴回零PLC启动程序", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CLOSE
        ///OPEN PLC 3 CLEAR
        ///IF(P801=1)AND(M122=0)
        ///	I113=0
        ///	I114=0
        ///	I122=32
        ///	COMMAND&quot;#1J-&quot;  
        ///	P801=2
        ///ELSE   
        ///	IF(P801=2)    
        ///		IF(M120=1)  
        ///			COMMAND&quot;#1J/&quot; 
        ///			P801=3
        ///		ENDIF
        ///		IF(M122=1)   
        ///			P801=-1
        ///			M172=200000
        ///			COMMAND&quot;#1J^*&quot;
        ///			P813=0
        ///		ENDIF
        ///	ENDIF
        ///	IF(P801=3)AND(M140=1) 
        ///		I123=-1   
        ///		I7013=0   
        ///		I7012=15   
        ///		COMMAND&quot;#1HOME&quot;   
        ///		P801=4
        ///	ENDIF
        ///	IF(P801=4)AND(M162&lt;4000)AND(M162&gt;-4000) 
        ///		P801=5
        ///	ENDIF
        ///	IF(P801=5)AND(M117=0)  
        ///		COMMAND&quot;#1HOMEZ&quot;
        ///		P801=6
        ///		I113=8840 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string 两轴回零PLC程序 {
            get {
                return ResourceManager.GetString("两轴回零PLC程序", resourceCulture);
            }
        }
    }
}
